name: Build docker image

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set build version
      run: sed -i -e "s/unknown/${GITHUB_SHA}/g" ./src/main/scala/com/github/frankivo/Version.scala
    - name: Test version
      run: cat ./src/main/scala/com/github/frankivo/Version.scala
    - name: Run tests
      run: sbt test
