name: Build docker image

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set build version
      run: sed -i -e "s/unknown/${GITHUB_SHA}/g" ./src/main/scala/com/github/frankivo/Version.scala

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: oosterhuisf
        password: ${{ secrets.DOCKERHUB }}

    - name: Build
      run: sbt "Docker / publish"
